---
title: "AMoNet GridSearch"
author: "Loic Verlingue"
date: "19 septembre 2019"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{AMoNet_GridSearch}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---

# Set working directory
Where to store the models and do the plotting

```{r setup}
knitr::opts_knit$set(root.dir = "C:/Users/L_VERLINGUE/Desktop/ModelK/Rpack/AMoNet")#

```


```{r}
# check you directory
print(getwd())
```


# Load (and optionally install) AMoNet package

```{r}

XV<-try(library(AMoNet),silent = T)

if("try-error"%in%class(XV)){
  print("Installing AMoNet from gitlab. Check your ID and pwd")
  devtools::install_git("https://user:password@gitlab.curie.fr/lverling/amonet.git", dependencies = TRUE)
  library(AMoNet)
} else {
  print("AMoNet loaded")
}


```

# Locate your wrapper scripts

```{r}

DirWrapperGS<-system.file('R/RunTCGAopt_HPC.R', package='AMoNet')
print(DirWrapperGS)

DirWrapperDraw<-system.file('R/DrawGridSearch.R', package='AMoNet')
print(DirWrapperDraw)

```

# On local computer

```{r}
# set arguments
args<-"--Param nblayers MinConnect --NameProj LUNG_AMoNet_new --GENESman EGFR MTOR --treatmt --Interval 10 --SelectMECA HALLMARK --organ luad --lambda 0.01 --alpha 1 --learningrate 0.001 --iteration 20"

# set the number of training trials
Ntrials<-3

# run with arguments in a loop
for( i in seq(Ntrials)){
  source(file = DirWrapperGS)
}

```

# Draw grid search results

```{r}
args<-"--NameProj LUNG_AMoNet_new --Validation T"

source(DirWrapperDraw)

```


# Locate HPC

```{r, eval=FALSE}

session <- ssh::ssh_connect("lverling@calcsub.curie.fr")
print(session)

#system(DirWorkflow)
DirWorkflow<-system.file("bash/",package = "AMoNet")
DirWorkflow<-file.path(DirWorkflow, list.files(DirWorkflow))

#DirPack<-gsub("AMoNet.*","AMoNet", DirWorkflow)

DirHPC<-"/data/tmp/lverling"

ssh::scp_upload(session, files = c(DirWorkflow, DirWrapperGS, DirWrapperDraw), to = DirHPC,verbose = T)

# run permission
#out<-ssh::ssh_exec_wait(session,command = paste("dos2unix ",DirHPC,"/*",sep = "") )
out<-ssh::ssh_exec_wait(session,command = paste("chmod 777 ",DirHPC,"/*",sep = "") )

# run workflow
ssh::ssh_exec_wait(session,command = c(paste("cd",DirHPC),"pwd", "sh workflow1.sh"))

outrun<-ssh::ssh_exec_internal(session,command = c(paste("cd",DirHPC),"pwd", "sh workflow.sh"))

#ssh::ssh_exec_wait(session,command = c(paste("cd",DirHPC), paste("sh",file.path(DirHPC, "workflow.sh"))))
#out<-ssh::ssh_exec_wait(session,command = file.path(DirHPC, "workflow.sh"))
#ssh::ssh_exec_wait(session,command = 'sh /data/tmp/lverling/workflow1.sh')

```

```{r}
out<-gsub(".torque6.curie.fr","", unlist(strsplit(rawToChar(outrun$stdout),"\n")))

for(i in seq(10)){
  out[length(out)+1]<-paste("TCGATrain.o", gsub("\\[\\]",paste("-",i,sep = ""),out[2]), sep = "")
  
  ssh::scp_download(session, files = file.path(DirHPC, out[length(out)]),to = file.path(getwd(),"tmp"))

}

#ssh::ssh_tunnel(session,port = 22,target = "calcsub.curie.fr:22")

#LF<-ssh::ssh_exec_internal(session,command = c(paste("cd",DirHPC),"ls -l"))


```



#
```{r}
ssh::ssh_disconnect(session)
```

